# datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aluraflix-db
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

# jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true

# log
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: trace
